# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjudication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_no', models.CharField(max_length=20)),
                ('determination_order', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('LANDLORD', 'landlord'), ('TENANT', 'tenant')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_no', models.CharField(max_length=20)),
                ('determination_order', models.CharField(max_length=100)),
                ('tr_no', models.CharField(max_length=20)),
                ('tribunal_report', models.CharField(max_length=100)),
                ('hearing_date', models.DateField()),
                ('appellant', models.ManyToManyField(related_name='appellant_parties', to='cases.Party')),
                ('respondent', models.ManyToManyField(related_name='trb_respondent_parties', to='cases.Party')),
                ('subject_of_dispute', models.ManyToManyField(to='cases.Subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adjudication',
            name='applicant',
            field=models.ManyToManyField(related_name='applicant_parties', to='cases.Party'),
        ),
        migrations.AddField(
            model_name='adjudication',
            name='respondent',
            field=models.ManyToManyField(related_name='adj_respondent_parties', to='cases.Party'),
        ),
        migrations.AddField(
            model_name='adjudication',
            name='subject_of_dispute',
            field=models.ManyToManyField(to='cases.Subject'),
        ),
    ]
