# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='role',
            field=models.CharField(choices=[('LANDLORD', 'landlord'), ('TENANT', 'tenant')], max_length=10, null=True),
        ),
    ]
