# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20170102_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_no', models.CharField(max_length=50)),
                ('case_type', models.CharField(choices=[(b'TRIBUNAL', b'tribunal'), (b'ADJUDICATION', b'adjudication')], max_length=15)),
                ('determination_order', models.CharField(max_length=300)),
                ('tribunal_report', models.CharField(max_length=300, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='adjudication',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='adjudication',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='adjudication',
            name='subject_of_dispute',
        ),
        migrations.RemoveField(
            model_name='tribunal',
            name='appellant',
        ),
        migrations.RemoveField(
            model_name='tribunal',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='tribunal',
            name='subject_of_dispute',
        ),
        migrations.AlterField(
            model_name='party',
            name='role',
            field=models.CharField(choices=[(b'LANDLORD', b'landlord'), (b'TENANT', b'tenant'), (b'THIRD_PARTY', b'third party')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Adjudication',
        ),
        migrations.DeleteModel(
            name='Tribunal',
        ),
        migrations.AddField(
            model_name='case',
            name='applicants',
            field=models.ManyToManyField(related_name='applicants', to='cases.Party'),
        ),
        migrations.AddField(
            model_name='case',
            name='respondents',
            field=models.ManyToManyField(related_name='respondents', to='cases.Party'),
        ),
        migrations.AddField(
            model_name='case',
            name='subjects_of_dispute',
            field=models.ManyToManyField(to='cases.Subject'),
        ),
    ]
