# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20170106_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='role',
            field=models.CharField(choices=[(b'LANDLORD', b'landlord'), (b'TENANT', b'tenant'), (b'THIRD_PARTY', b'third party')], max_length=20, null=True),
        ),
    ]
