# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20170106_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together=set([('dr_no', 'case_type', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='party',
            unique_together=set([('name', 'role')]),
        ),
    ]
