# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20170106_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='tr_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
