# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20170112_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
